"""ORCA-like reports for dense-validation and matrix-free calculations."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from .mrsf import HARTREE_TO_EV
from .observables import BOHR_TO_ANGSTROM
from .solvent import pcm_metadata
from .symmetry import orbital_irrep_names, term_labels


def _line(handle, character: str = "-", width: int = 79) -> None:
    handle.write(character * width + "\n")


def _basis_label(mol) -> str:
    basis = getattr(mol, "basis", "unknown")
    if isinstance(basis, str):
        return basis
    if isinstance(basis, dict):
        values = sorted({str(value) for value in basis.values()})
        return ", ".join(values)
    return str(basis)


def _value_label(value) -> str:
    """Return a compact label for scalar, dictionary, or per-atom settings."""

    if value is None:
        return "none"
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        items = sorted({str(item) for item in value.values()})
        return ", ".join(items)
    return str(value)


def _method_label(ref) -> str:
    mf = ref.mf
    if hasattr(mf, "xc"):
        return f"ROKS/{mf.xc}"
    return "ROHF"


def _write_header(
    handle,
    ref,
    *,
    calculation: str,
    target_multiplicity: int,
    title: str | None,
) -> None:
    mol = ref.mf.mol
    _line(handle, "=")
    handle.write("                  P y S C F - E M R S F\n")
    handle.write("    EMRSF-SOC/eigenvector export release v0.8.0\n")
    _line(handle, "=")
    handle.write("This is an ORCA-style human-readable report generated by\n")
    handle.write("PySCF-EMRSF.  It is not an ORCA output file.\n\n")
    handle.write(f"JOB TITLE            {title or 'untitled'}\n")
    handle.write(f"CALCULATION          {calculation}\n")
    handle.write(f"METHOD               {_method_label(ref)}\n")
    handle.write(f"BASIS                {_basis_label(mol)}\n")
    with_df = getattr(ref.mf, "with_df", None)
    handle.write(f"DENSITY FITTING      {with_df is not None}\n")
    if with_df is not None:
        handle.write(
            f"AUXILIARY BASIS      {_value_label(getattr(with_df, 'auxbasis', None))}\n"
        )
    if hasattr(ref.mf, "xc"):
        grid = getattr(ref.mf, "grids", None)
        handle.write(
            f"SCF XC GRID LEVEL    {getattr(grid, 'level', 'unknown')}\n"
        )
        coordinates = getattr(grid, "coords", None)
        points = len(coordinates) if coordinates is not None else 0
        handle.write(f"SCF XC GRID POINTS   {points:d}\n")
        handle.write(
            f"SCF XC GRID PRUNED   {getattr(grid, 'prune', None) is not None}\n"
        )
    pcm = pcm_metadata(ref.mf)
    if pcm is None:
        handle.write("PCM SOLVATION        False\n")
    else:
        handle.write("PCM SOLVATION        True\n")
        handle.write(f"PCM METHOD           {pcm['method']}\n")
        handle.write(f"PCM EPSILON          {float(pcm['epsilon']):.8f}\n")
        handle.write(f"PCM LEBEDEV ORDER    {int(pcm['lebedev_order'])}\n")
        handle.write("PCM RESPONSE SCOPE   reference-state; frozen in MRSF/EMRSF response\n")
    handle.write(
        f"SCF CONV. TOL.      {float(getattr(ref.mf, 'conv_tol', np.nan)): .3e}\n"
    )
    handle.write(
        "SCF GRAD. TOL.      "
        f"{float(getattr(ref.mf, 'conv_tol_grad', None) or np.nan): .3e}\n"
    )
    handle.write(
        "DIRECT SCF TOL.     "
        f"{float(getattr(ref.mf, 'direct_scf_tol', np.nan)): .3e}\n"
    )
    if hasattr(ref.mf, "small_rho_cutoff"):
        handle.write(
            "SMALL RHO CUTOFF    "
            f"{float(ref.mf.small_rho_cutoff): .3e}\n"
        )
    handle.write(f"SCF MAX CYCLES      {int(getattr(ref.mf, 'max_cycle', 0)):d}\n")
    handle.write(f"MOLECULAR CHARGE     {mol.charge:d}\n")
    handle.write(f"REFERENCE MULT.      {mol.spin + 1:d}\n")
    handle.write(f"TARGET MULT.         {int(target_multiplicity):d}\n")
    handle.write(f"POINT GROUP          {getattr(mol, 'groupname', 'C1') or 'C1'}\n")
    handle.write(f"ELECTRONS            {mol.nelectron:d}\n")
    handle.write(f"AO FUNCTIONS         {ref.nao:d}\n")
    handle.write(f"MO FUNCTIONS         {ref.nmo:d}\n")
    run_metadata = dict(getattr(ref.mf, "emrsf_run_metadata", {}))
    if run_metadata:
        handle.write(
            f"RESPONSE METHOD       {run_metadata.get('method', 'unknown')}\n"
        )
        handle.write(
            "RESPONSE INTEGRALS    "
            f"{run_metadata.get('integral_backend', 'unknown')}\n"
        )
        handle.write(
            "RESPONSE EIG. TOL.    "
            f"{float(run_metadata.get('eigenvalue_tolerance', np.nan)): .3e}\n"
        )
        handle.write(
            "RESPONSE RES. TOL.    "
            f"{float(run_metadata.get('residual_tolerance', np.nan)): .3e}\n"
        )
    handle.write(f"TIMESTAMP UTC        {datetime.now(timezone.utc).isoformat()}\n")


def _write_geometry(handle, ref) -> None:
    mol = ref.mf.mol
    coordinates = np.asarray(mol.atom_coords()) * BOHR_TO_ANGSTROM
    handle.write("\nCARTESIAN COORDINATES (ANGSTROEM)\n")
    _line(handle)
    handle.write("  No. Element              X              Y              Z\n")
    for atom, coordinate in enumerate(coordinates):
        handle.write(
            f"{atom + 1:5d} {mol.atom_symbol(atom):>3s}"
            f" {coordinate[0]:14.8f} {coordinate[1]:14.8f} {coordinate[2]:14.8f}\n"
        )


def _write_reference(handle, ref) -> None:
    mf = ref.mf
    diagnostics = ref.diagnostics
    metadata = dict(getattr(mf, "emrsf_reference_metadata", {}))
    handle.write("\nTRIPLET REFERENCE\n")
    _line(handle)
    handle.write(f"REFERENCE SOURCE      {diagnostics.source}\n")
    if diagnostics.source_path:
        handle.write(f"REFERENCE SOURCE FILE {diagnostics.source_path}\n")
    handle.write(f"LOCAL SCF RUN         {diagnostics.local_scf_run}\n")
    handle.write(f"LOCAL SCF CONVERGED   {diagnostics.local_scf_converged}\n")
    handle.write(f"REFERENCE READY       {bool(getattr(mf, 'converged', False))}\n")
    if metadata.get("scf_strategy") is not None:
        handle.write(f"SCF STRATEGY          {metadata['scf_strategy']}\n")
        handle.write(
            f"SCF FINAL STAGE       {metadata.get('scf_final_stage', 'unknown')}\n"
        )
        handle.write(
            f"SCF RESCUE USED       {bool(metadata.get('scf_rescue_used', False))}\n"
        )
        handle.write(
            "SCF 2-CYCLE DETECTED "
            f"{bool(metadata.get('scf_oscillation_detected', False))}\n"
        )
        handle.write(
            "SCF DENSITY AVG GUESS "
            f"{bool(metadata.get('scf_density_averaging_used', False))}\n"
        )
        attempts = tuple(metadata.get("scf_attempt_history", ()))
        handle.write(f"SCF ATTEMPT COUNT     {len(attempts):d}\n")
        for index, attempt in enumerate(attempts, start=1):
            handle.write(
                f"SCF ATTEMPT {index:02d}        "
                f"{attempt.get('name', 'unknown')} | "
                f"{attempt.get('converger', 'unknown')} | "
                f"converged={bool(attempt.get('converged', False))} | "
                f"cycles={int(attempt.get('cycles', 0))} | "
                f"E={float(attempt.get('energy_hartree', np.nan)):.12f} Eh | "
                f"g={float(attempt.get('gradient_norm', np.nan)):.3e} | "
                f"dP={float(attempt.get('density_change_norm', np.nan)):.3e} | "
                "two_cycle="
                f"{bool(attempt.get('oscillation_detected', False))}\n"
            )
    handle.write(f"SCF ENERGY / Eh       {float(getattr(mf, 'e_tot', np.nan)): .14f}\n")
    handle.write(f"CLOSED ORBITALS       {len(ref.closed):d}\n")
    handle.write(f"OPEN ORBITALS O1/O2   {ref.o1 + 1:d}  {ref.o2 + 1:d}\n")
    handle.write(f"VIRTUAL ORBITALS      {len(ref.virtual):d}\n")
    if metadata.get("input_orthonormality_error") is not None:
        handle.write(
            "MOLDEN INPUT S-ORTH ERR "
            f"{float(metadata['input_orthonormality_error']): .6e}\n"
        )
    if metadata.get("basis_projection") is not None:
        handle.write(
            f"MOLDEN BASIS PROJECTED {bool(metadata['basis_projection'])}\n"
        )
    handle.write(
        f"FINAL S-ORTH ERROR    {diagnostics.orthonormality_error: .6e}\n"
    )
    handle.write(
        f"ELECTRON TRACE ERROR  {diagnostics.electron_number_error: .6e}\n"
    )
    handle.write(f"SPIN TRACE ERROR      {diagnostics.spin_number_error: .6e}\n")
    handle.write(
        f"ORBITAL GRADIENT MAX  {diagnostics.orbital_gradient_max: .6e}\n"
    )
    handle.write(
        f"ORBITAL GRADIENT RMS  {diagnostics.orbital_gradient_rms: .6e}\n"
    )
    handle.write(
        "MIN ORBITAL SYM WEIGHT "
        f"{diagnostics.minimum_orbital_symmetry_weight: .10f}\n"
    )
    handle.write(
        "GAP CLOSED->O1 / Eh "
        f"{diagnostics.closed_to_o1_gap_hartree: .10f}\n"
    )
    handle.write(
        f"GAP O1->O2 / Eh       {diagnostics.o1_to_o2_gap_hartree: .10f}\n"
    )
    handle.write(
        "GAP O2->VIRTUAL / Eh "
        f"{diagnostics.o2_to_virtual_gap_hartree: .10f}\n"
    )
    if diagnostics.seed_somo_singular_values:
        values = " ".join(
            f"{value:.10f}" for value in diagnostics.seed_somo_singular_values
        )
        handle.write(f"SEED SOMO SINGULAR VAL {values}\n")
    if diagnostics.seed_alpha_occupied_min_singular_value is not None:
        handle.write(
            "SEED ALPHA OCC MIN SV "
            f"{diagnostics.seed_alpha_occupied_min_singular_value:.10f}\n"
        )
    if diagnostics.seed_beta_occupied_min_singular_value is not None:
        handle.write(
            "SEED BETA OCC MIN SV  "
            f"{diagnostics.seed_beta_occupied_min_singular_value:.10f}\n"
        )
    handle.write(
        "REFERENCE WARNINGS    "
        + (", ".join(diagnostics.warnings) if diagnostics.warnings else "NONE")
        + "\n"
    )
    handle.write("\nORBITAL ENERGIES\n")
    handle.write("  MO   SYM       OCC          EPSILON / Eh          EPSILON / eV\n")
    irreps = orbital_irrep_names(ref)
    for orbital, (occupation, energy, irrep) in enumerate(
        zip(ref.occupation, ref.energy, irreps), start=1
    ):
        handle.write(
            f"{orbital:5d} {irrep:>5s} {occupation:9.4f} {energy:21.12f}"
            f" {energy * HARTREE_TO_EV:21.8f}\n"
        )


def _mrsf_configuration_name(space, pair: tuple[int, int]) -> str:
    i, a = pair
    ref = space.ref
    if pair == (ref.o2, ref.o1):
        return "G"
    if pair == (ref.o1, ref.o2):
        return "D"
    if pair == (ref.o1, ref.o1):
        return "OOS"
    if i in set(ref.closed) and a == ref.o1:
        return "CO1"
    if i in set(ref.closed) and a == ref.o2:
        return "CO2"
    if i == ref.o1 and a in set(ref.virtual):
        return "O1V"
    if i == ref.o2 and a in set(ref.virtual):
        return "O2V"
    if i in set(ref.closed) and a in set(ref.virtual):
        return "CV(MRSF)"
    return "MRSF"


def _write_mrsf_configurations(
    handle, result, state: int, *, top_configurations: int
) -> None:
    vector = result.eigenvectors[:, state]
    order = np.argsort(np.abs(vector))[::-1]
    printed = 0
    for index in order:
        amplitude = float(vector[index])
        if abs(amplitude) < 1.0e-10:
            continue
        i, a = result.space.labels[index]
        name = _mrsf_configuration_name(result.space, (i, a))
        handle.write(
            f"    {name:<10s} {i + 1:5d} -> {a + 1:<5d}"
            f"  c={amplitude: .9f}  w={amplitude * amplitude: .9f}\n"
        )
        printed += 1
        if printed >= top_configurations:
            break


def _write_mrsf_states(handle, result, *, top_configurations: int) -> None:
    manifold = "SINGLET" if result.target_multiplicity == 1 else "TRIPLET"
    state0 = "singlet" if result.target_multiplicity == 1 else "triplet"
    handle.write(f"\nMRSF-TDDFT/TDA {manifold} STATES\n")
    _line(handle)
    handle.write("Root energies are relative to the high-spin response reference;\n")
    handle.write(
        f"excitation energies are relative to the lowest MRSF {state0} root.\n\n"
    )
    symmetries = result.state_symmetries()
    terms = term_labels(symmetries)
    for state, energy in enumerate(result.eigenvalues):
        state_symmetry = symmetries[state]
        handle.write(
            f"STATE {state:3d}: E={energy: .12f} Eh"
            f"  EXC={result.excitation_energies_ev[state]: .8f} eV"
            f"  SYM={state_symmetry.label}"
            f"  TERM={terms[state]}"
            f"  PURITY={state_symmetry.purity: .8f}\n"
        )
        _write_mrsf_configurations(
            handle, result, state, top_configurations=top_configurations
        )


def _write_solver_diagnostics(handle, result, label: str) -> None:
    handle.write(f"\n{label} EIGENSOLVER\n")
    _line(handle)
    handle.write(f"SOLVER               {result.solver}\n")
    handle.write(
        f"MATRIX STORAGE       {'DENSE' if result.matrix is not None else 'MATRIX-FREE'}\n"
    )
    if result.iterations is not None:
        handle.write(f"ITERATIONS           {result.iterations:d}\n")
    if result.matvecs is not None:
        handle.write(f"MATVECS              {result.matvecs:d}\n")
    if result.initial_guesses is not None:
        handle.write(f"INITIAL GUESSES      {result.initial_guesses:d}\n")
    if result.symmetry_seed_counts:
        if hasattr(result, "space"):
            groupname = result.space.ref.mf.mol.groupname
        elif hasattr(result, "mrsf_space"):
            groupname = result.mrsf_space.ref.mf.mol.groupname
        else:
            groupname = result.mrsf_result.space.ref.mf.mol.groupname
        from pyscf import symm

        values = []
        for irrep_id, count in result.symmetry_seed_counts:
            try:
                label_name = symm.irrep_id2name(groupname, int(irrep_id))
            except (KeyError, ValueError):
                label_name = str(irrep_id)
            values.append(f"{label_name}:{count}")
        handle.write(f"SEEDS PER IRREP      {' '.join(values)}\n")
    if result.converged is not None:
        handle.write(
            "ROOTS CONVERGED      "
            f"{int(np.count_nonzero(result.converged)):d}/{len(result.converged):d}\n"
        )
    if result.residual_norms is not None:
        handle.write(
            f"MAX RESIDUAL NORM    {float(np.max(result.residual_norms)): .6e}\n"
        )


def _descriptor_map(descriptors) -> dict[int, object]:
    if descriptors is None:
        return {}
    return {int(value.state_index): value for value in descriptors}


def _write_descriptors(handle, descriptors) -> None:
    values = _descriptor_map(descriptors)
    if not values:
        return
    handle.write("\nDENSITY-DIFFERENCE CHARGE-TRANSFER ANALYSIS (SI S42-S47)\n")
    _line(handle)
    handle.write("rho_ref is the triplet-reference density.  q is the symmetric\n")
    handle.write("average of the finite-grid positive and negative integrals.\n")
    handle.write("Both S45 centroids use this common q denominator, as printed in SI.\n")
    handle.write("mu=q*D_CT is reported in e*Angstrom (paper convention), e*bohr,\n")
    handle.write("and Debye.  Integral residuals expose quadrature convergence.\n")
    for state in sorted(values):
        value = values[state]
        handle.write(f"\nMRSF STATE {state:d}\n")
        handle.write(f"  S42  integral Delta rho       {value.integral_delta_rho: .10e} e\n")
        handle.write(f"  S43  positive/negative fields evaluated on molecular grid\n")
        handle.write(f"  S44  q+                       {value.q_plus: .10f} e\n")
        handle.write(f"       q-                       {value.q_minus: .10f} e\n")
        handle.write(f"       q=(q+ + q-)/2            {value.q: .10f} e\n")
        handle.write(f"       q+ - q-                  {value.charge_imbalance: .10e} e\n")
        handle.write(
            "  S45  R+ / Angstrom            "
            f"{value.r_plus_angstrom[0]: .8f} {value.r_plus_angstrom[1]: .8f}"
            f" {value.r_plus_angstrom[2]: .8f}\n"
        )
        handle.write(
            "       R- / Angstrom            "
            f"{value.r_minus_angstrom[0]: .8f} {value.r_minus_angstrom[1]: .8f}"
            f" {value.r_minus_angstrom[2]: .8f}\n"
        )
        handle.write(f"  S46  D_CT                     {value.d_ct_angstrom: .10f} Angstrom\n")
        handle.write(f"                                {value.d_ct_bohr: .10f} bohr\n")
        handle.write(f"  S47  mu=q*D_CT                {value.mu_e_angstrom: .10f} e*Angstrom\n")
        handle.write(f"                                {value.mu_e_bohr: .10f} e*bohr\n")
        handle.write(f"                                {value.mu_debye: .10f} Debye\n")
        handle.write(
            f"  GRID level/points/pruned      {value.grid_level:d} /"
            f" {value.grid_points:d} / {value.grid_pruned}\n"
        )
        handle.write(
            f"  GRID electrons ref/state      {value.reference_electrons_grid: .10f} /"
            f" {value.state_electrons_grid: .10f}\n"
        )


def _write_transition_properties(
    handle, properties, *, target_multiplicity: int = 1
) -> None:
    if not properties:
        return
    handle.write("\nMRSF ELECTRIC-DIPOLE TRANSITION PROPERTIES (LENGTH GAUGE)\n")
    _line(handle)
    handle.write(
        "Properties use the spin-adapted MRSF state-to-state transition 1-RDM.\n"
    )
    manifold = "S0 -> Sn" if int(target_multiplicity) == 1 else "T0 -> Tn"
    handle.write(f"TRANSITION MANIFOLD  {manifold}\n")
    handle.write("Dipoles are in e*bohr.  When printed in an EMRSF report, these\n")
    handle.write("are explicitly the companion MRSF values, not full EMRSF strengths.\n\n")
    handle.write(
        " INITIAL FINAL      DELTA_E/eV          MUX          MUY          MUZ"
        "       |MU|             f       Tr(D_if)\n"
    )
    for value in properties:
        dipole = value.transition_dipole_e_bohr
        handle.write(
            f" {value.initial_state:7d} {value.final_state:5d}"
            f" {value.excitation_energy_ev:15.8f}"
            f" {dipole[0]:12.7f} {dipole[1]:12.7f} {dipole[2]:12.7f}"
            f" {value.transition_dipole_norm_e_bohr:10.7f}"
            f" {value.oscillator_strength:13.8f}"
            f" {value.transition_density_trace:13.5e}\n"
        )


def _write_emrsf_configurations(
    handle, result, state: int, *, top_configurations: int
) -> None:
    vector = result.eigenvectors[:, state]
    mrsf_space = result.mrsf_space
    entries = []
    for reduced, full in enumerate(result.live_mrsf_indices):
        i, a = mrsf_space.labels[int(full)]
        entries.append(
            (
                abs(vector[reduced]),
                vector[reduced],
                _mrsf_configuration_name(mrsf_space, (i, a)),
                i,
                a,
            )
        )
    for offset, (i, a) in enumerate(result.cv_space.labels):
        index = result.mrsf_size + offset
        entries.append((abs(vector[index]), vector[index], "CV(LR)", i, a))
    entries.sort(key=lambda item: item[0], reverse=True)
    for _, amplitude, name, i, a in entries[:top_configurations]:
        handle.write(
            f"    {name:<10s} {i + 1:5d} -> {a + 1:<5d}"
            f"  c={amplitude: .9f}  w={amplitude * amplitude: .9f}\n"
        )


def _write_emrsf_states(handle, result, *, top_configurations: int) -> None:
    manifold = "SINGLET" if result.target_multiplicity == 1 else "TRIPLET"
    state0 = "singlet" if result.target_multiplicity == 1 else "triplet"
    handle.write(f"\nEMRSF-TDDFT/TDA {manifold} STATES\n")
    _line(handle)
    handle.write("gamma_CV is the squared norm of the added LR C->V sector.\n\n")
    handle.write(
        f"EXC energies are relative to the lowest EMRSF {state0} root. "
        "For vertical triplet benchmarks use the separately reported common "
        "singlet-S0 origin.\n\n"
    )
    symmetries = result.state_symmetries()
    terms = term_labels(symmetries)
    for state, energy in enumerate(result.eigenvalues):
        state_symmetry = symmetries[state]
        handle.write(
            f"STATE {state:3d}: E={energy: .12f} Eh"
            f"  EXC={result.excitation_energies_ev[state]: .8f} eV"
            f"  SYM={state_symmetry.label}"
            f"  TERM={terms[state]}"
            f"  PURITY={state_symmetry.purity: .8f}"
            f"  gamma_CV={result.cv_weights[state]: .8f}\n"
        )
        _write_emrsf_configurations(
            handle, result, state, top_configurations=top_configurations
        )


def _write_state_correlations(handle, result, descriptors) -> None:
    descriptor_by_state = _descriptor_map(descriptors)
    emrsf_symmetries = result.state_symmetries()
    mrsf_symmetries = result.mrsf_result.state_symmetries()
    emrsf_terms = term_labels(emrsf_symmetries)
    mrsf_terms = term_labels(mrsf_symmetries)
    handle.write("\nMRSF <-> EMRSF STATE CORRELATION\n")
    _line(handle)
    handle.write(
        "TERM matching is an ordinal-within-irrep diagnostic (for example, "
        "2 B1 with 2 B1); it is not an assumed paper-specific root map.\n"
    )
    handle.write(
        "Conditional overlap < 0.5 is flagged but does not redirect a term to a "
        "different state. CAND is the best-overlap diagnostic root; overlap "
        "columns refer to MR, or to CAND when MR is --.\n"
    )
    handle.write(
        " EM  MR CAND  EMTERM  MRTERM STATUS                         gamma_CV"
        "   |<MR|EM>|^2   conditional   dE(abs)/eV  dE(exc)/eV    mu/eA\n"
    )
    for match in result.state_matches():
        descriptor = (
            descriptor_by_state.get(match.mrsf_state)
            if match.matched
            else None
        )
        mu = descriptor.mu_e_angstrom if descriptor is not None else np.nan
        mr_text = f"{match.mrsf_state:3d}" if match.matched else " --"
        candidate_text = (
            f"{match.candidate_mrsf_state:4d}"
            if match.candidate_mrsf_state is not None
            else "  --"
        )
        mr_term = (
            mrsf_terms[match.mrsf_state]
            if match.matched
            else "--"
        )
        handle.write(
            f"{match.emrsf_state:3d} {mr_text} {candidate_text}"
            f" {emrsf_terms[match.emrsf_state]:>7s}"
            f" {mr_term:>7s}"
            f" {match.status:<30s}"
            f" {result.cv_weights[match.emrsf_state]:12.8f}"
            f" {match.overlap_squared:14.8f}"
            f" {match.conditional_overlap_squared:13.8f}"
            f" {match.raw_energy_shift_ev:12.7f}"
            f" {match.excitation_energy_shift_ev:12.7f}"
            f" {mu:10.6f}\n"
        )


def _write_emrsf_decompositions(handle, result) -> None:
    if not result.state_decompositions:
        return
    handle.write("\nEMRSF EIGENVALUE BLOCK DECOMPOSITION\n")
    _line(handle)
    handle.write(
        "For each normalized enlarged-space eigenvector, E is reconstructed as\n"
    )
    handle.write(
        "<X_M|A_MRSF|X_M> + <X_CV|A_CV+A_G|X_CV> "
        "+ 2<X_M|C|X_CV>.\n"
    )
    handle.write(
        " STATE      W_MRSF       W_CV       MRSF/Eh         CV/Eh"
        "      2C/Eh       closure/Eh\n"
    )
    for value in result.state_decompositions:
        handle.write(
            f" {value.state:5d}"
            f" {value.mrsf_weight:12.8f}"
            f" {value.cv_weight:12.8f}"
            f" {value.mrsf_block_hartree:14.8f}"
            f" {value.cv_block_hartree:14.8f}"
            f" {value.coupling_hartree:12.8f}"
            f" {value.closure_error_hartree:16.6e}\n"
        )


def _write_footer(handle) -> None:
    handle.write("\n")
    _line(handle, "=")
    handle.write("               **** PYSCF-EMRSF NORMAL TERMINATION ****\n")
    _line(handle, "=")


def _write_coupling_audit(handle, audit) -> None:
    if audit is None:
        return
    handle.write("\nGROUND-STATE MRSF--CV COUPLING AUDIT\n")
    _line(handle, "-")
    handle.write(
        "This section decomposes C.T|MRSF S0> without changing the EMRSF "
        "Hamiltonian.\n"
    )
    handle.write(
        "The diagonal second-order values use only diag(A_CV + A_G) as the "
        "resolvent and are diagnostics, not corrected energies.\n\n"
    )
    handle.write(f"COUPLING SCALE c_cp       {audit.coupling_scale: .12f}\n")
    handle.write("G SPIN FACTOR             sqrt(2), fixed by Table S3\n")
    handle.write("CO1/O2V COMBINATION       S1-S2, fixed by spin adaptation\n")
    handle.write(
        f"MRSF S0 ENERGY            {audit.mrsf_ground_energy_hartree: .12f} Eh\n"
    )
    handle.write(
        f"EMRSF S0 ENERGY           {audit.emrsf_ground_energy_hartree: .12f} Eh\n"
    )
    handle.write(
        f"EXACT S0 SHIFT            {audit.exact_ground_shift_hartree: .12f} Eh"
        f"  {audit.exact_ground_shift_ev: .8f} eV\n"
    )
    handle.write(f"EMRSF S0 gamma_CV         {audit.gamma_cv_ground: .12f}\n")
    handle.write(f"||C.T S0||                {audit.coupling_norm: .12e}\n")
    handle.write(f"||Fock part||             {audit.fock_norm: .12e}\n")
    handle.write(f"||two-electron part||     {audit.two_electron_norm: .12e}\n")
    handle.write(
        f"<Fock|two-electron>       {audit.fock_two_electron_dot: .12e}\n"
    )
    handle.write(
        f"DIAG 2ND-ORDER S0 SHIFT   "
        f"{audit.diagonal_second_order_shift_hartree: .12f} Eh"
        f"  {audit.diagonal_second_order_shift_ev: .8f} eV\n"
    )
    handle.write(
        f"  Fock partition          {audit.diagonal_fock_partition_hartree: .12f} Eh"
        f"  {audit.diagonal_fock_partition_ev: .8f} eV\n"
    )
    handle.write(
        "  two-electron partition  "
        f"{audit.diagonal_two_electron_partition_hartree: .12f} Eh"
        f"  {audit.diagonal_two_electron_partition_ev: .8f} eV\n\n"
    )
    handle.write(
        " FAMILY       MRSF_W       ||C_f.T S0||   ||Fock||       ||2e||"
        "          self/eV    partition/eV\n"
    )
    for family in audit.families:
        handle.write(
            f" {family.name:<10s}"
            f" {family.mrsf_weight:11.8f}"
            f" {family.coupling_norm:15.7e}"
            f" {family.fock_norm:13.6e}"
            f" {family.two_electron_norm:13.6e}"
            f" {family.diagonal_self_shift_ev:11.7f}"
            f" {family.diagonal_partition_shift_ev:15.7f}\n"
        )


def _write_lr_cv_diagonal_audit(handle, audit) -> None:
    if audit is None:
        return
    handle.write("\nADDED LR-CV DIAGONAL AUDIT (SI S30-S39)\n")
    _line(handle, "-")
    handle.write(
        "Each A_CV diagonal is decomposed into the raw closed-shell Fock "
        "difference,\n"
    )
    handle.write(
        "the S30 correction, Coulomb response, global exact exchange, and "
        "the\n"
    )
    handle.write(
        "semilocal XC kernel. Explicit SI-S23 A_G is then added exactly once.\n"
    )
    handle.write(
        "All table entries are in Eh. CHECK rows are independently evaluated "
        "with\n"
    )
    handle.write("the complete matrix-free EMRSF operator.\n\n")
    handle.write(f"S30 APPLIED                 {audit.apply_fock_correction}\n")
    handle.write(f"GLOBAL HF EXCHANGE c_H      {audit.exact_exchange: .12f}\n")
    handle.write(f"AO RESPONSE BATCH SIZE      {audit.batch_size:d}\n")
    handle.write(
        f"A_G EXPLICIT SI S23         {audit.ground_offset_hartree: .12f} Eh"
        f"  {audit.ground_offset_hartree * HARTREE_TO_EV: .8f} eV\n"
    )
    handle.write(
        f"A_G FROM MRSF OPERATOR      "
        f"{audit.ground_offset_recomputed_hartree: .12f} Eh\n"
    )
    handle.write(
        f"A_G SOURCE ERROR            "
        f"{audit.ground_offset_source_error_hartree: .6e} Eh\n"
    )
    handle.write(
        f"MAX DIRECT DIAGONAL ERROR   "
        f"{audit.maximum_direct_check_error_hartree: .6e} Eh"
        f"  {audit.maximum_direct_check_error_ev: .6e} eV\n\n"
    )
    handle.write(
        " IDX      C -> V       raw Fock          S30            J"
        "          exact-X      semilocal-XC          A_G          total\n"
    )
    for index, (i, a) in enumerate(audit.labels):
        handle.write(
            f" {index:4d} {i + 1:6d} -> {a + 1:<6d}"
            f" {audit.raw_fock_hartree[index]:14.8f}"
            f" {audit.s30_hartree[index]:12.8f}"
            f" {audit.coulomb_hartree[index]:12.8f}"
            f" {audit.exact_exchange_hartree[index]:14.8f}"
            f" {audit.xc_kernel_hartree[index]:17.8f}"
            f" {audit.ground_offset_hartree:12.8f}"
            f" {audit.emrsf_diagonal_hartree[index]:14.8f}\n"
        )

    handle.write("\nREPRESENTATIVE COMPLETE-MATVEC CHECKS\n")
    handle.write(
        " IDX      C -> V        component sum       direct matvec"
        "          difference\n"
    )
    for position, index in enumerate(audit.direct_check_indices):
        i, a = audit.labels[int(index)]
        handle.write(
            f" {int(index):4d} {i + 1:6d} -> {a + 1:<6d}"
            f" {audit.emrsf_diagonal_hartree[index]:18.10f}"
            f" {audit.direct_check_hartree[position]:18.10f}"
            f" {audit.direct_check_error_hartree[position]:15.6e}\n"
        )


def write_mrsf_log(
    result,
    path,
    *,
    descriptors=None,
    transition_properties=None,
    title: str | None = None,
    top_configurations: int = 8,
) -> Path:
    """Write a complete MRSF report and return its path."""

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as handle:
        _write_header(
            handle,
            result.space.ref,
            calculation="MRSF-TDDFT/TDA",
            target_multiplicity=result.target_multiplicity,
            title=title,
        )
        _write_geometry(handle, result.space.ref)
        _write_reference(handle, result.space.ref)
        handle.write(f"\nRAW MRSF SPACE       {result.space.size:d}\n")
        handle.write(f"COMPUTED ROOTS       {len(result.eigenvalues):d}\n")
        _write_solver_diagnostics(handle, result, "MRSF")
        _write_mrsf_states(
            handle, result, top_configurations=int(top_configurations)
        )
        _write_descriptors(handle, descriptors)
        _write_transition_properties(
            handle,
            transition_properties,
            target_multiplicity=result.target_multiplicity,
        )
        _write_footer(handle)
    return output


def write_emrsf_log(
    result,
    path,
    *,
    descriptors=None,
    transition_properties=None,
    coupling_audit=None,
    lr_cv_audit=None,
    title: str | None = None,
    top_configurations: int = 8,
) -> Path:
    """Write MRSF, EMRSF, CV, state-matching, and S42--S47 information."""

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    ref = result.cv_space.ref
    with output.open("w", encoding="utf-8") as handle:
        _write_header(
            handle,
            ref,
            calculation="EMRSF-TDDFT/TDA",
            target_multiplicity=result.target_multiplicity,
            title=title,
        )
        _write_geometry(handle, ref)
        _write_reference(handle, ref)
        handle.write(f"\nRAW MRSF SPACE       {result.mrsf_space.size:d}\n")
        handle.write(f"LIVE MRSF SPACE      {result.mrsf_size:d}\n")
        handle.write(f"ADDED LR C->V SPACE  {result.cv_space.size:d}\n")
        handle.write(f"EMRSF OPERATOR DIM.  {result.eigenvectors.shape[0]:d}\n")
        handle.write(f"COMPUTED ROOTS       {len(result.eigenvalues):d}\n")
        handle.write(f"DIRECT EMRSF MODE    {result.direct_emrsf}\n")
        handle.write(
            "MRSF PRE-DIAGONAL.   "
            f"{result.mrsf_result is not None}\n"
        )
        handle.write(f"INTEGRAL BACKEND     {result.integral_backend}\n")
        if result.exact_exchange is not None:
            handle.write(f"HF EXCHANGE c_H      {result.exact_exchange: .12f}\n")
        if result.coupling_scale is not None:
            handle.write(f"COUPLING SCALE c_cp  {result.coupling_scale: .12f}\n")
        if result.target_multiplicity == 1:
            handle.write("G SPIN FACTOR        sqrt(2), fixed by Table S3\n")
            handle.write("OOS SPIN COMBINATION (L-R)/sqrt(2)\n")
            handle.write("CO1 TABLE COMBINATION S1-S2, fixed\n")
            handle.write("O2V TABLE COMBINATION S1-S2, fixed\n")
        else:
            handle.write("G/D CONFIGURATIONS   absent from triplet space\n")
            handle.write("OOS SPIN COMBINATION (L+R)/sqrt(2)\n")
            handle.write("CO1 TABLE COMBINATION S1+S2, fixed\n")
            handle.write("O2V TABLE COMBINATION S1+S2, fixed\n")
        handle.write("COUPLING FORM         c_cp * <MRSF|H|CV>\n")
        if result.ground_offset_hartree is not None:
            handle.write(
                f"GROUND OFFSET A_G     {result.ground_offset_hartree: .12f} Eh"
                f"  {result.ground_offset_hartree * HARTREE_TO_EV: .8f} eV\n"
            )
        if result.ground_offset_operator_hartree is not None:
            handle.write(
                "A_G OPERATOR CHECK    "
                f"{result.ground_offset_operator_hartree: .12f} Eh\n"
            )
        if result.ground_offset_source_error_hartree is not None:
            handle.write(
                "A_G CHECK ERROR       "
                f"{result.ground_offset_source_error_hartree: .6e} Eh\n"
            )
        if result.coupling_frobenius_norm is None:
            handle.write("COUPLING FROB. NORM   not assembled (matrix-free)\n")
        else:
            handle.write(
                f"COUPLING FROB. NORM   {result.coupling_frobenius_norm: .12e}\n"
            )
        if result.mrsf_result is not None:
            _write_solver_diagnostics(handle, result.mrsf_result, "MRSF")
        else:
            handle.write("\nMRSF EIGENSOLVER\n")
            _line(handle)
            handle.write("NOT RUN              direct enlarged-space EMRSF mode\n")
        _write_solver_diagnostics(handle, result, "EMRSF")
        if result.mrsf_result is not None:
            _write_mrsf_states(
                handle,
                result.mrsf_result,
                top_configurations=int(top_configurations),
            )
        _write_emrsf_states(
            handle, result, top_configurations=int(top_configurations)
        )
        _write_emrsf_decompositions(handle, result)
        if result.mrsf_result is not None:
            _write_state_correlations(handle, result, descriptors)
        _write_descriptors(handle, descriptors)
        _write_transition_properties(
            handle,
            transition_properties,
            target_multiplicity=result.target_multiplicity,
        )
        _write_coupling_audit(handle, coupling_audit)
        _write_lr_cv_diagonal_audit(handle, lr_cv_audit)
        _write_footer(handle)
    return output
